export default {
  subjects: [
    {value: "", label: "Choose a specialty"},
    {value: "ZC", label: "ACUPUNCTURE"},
    {value: "DEC01", label: "ADDICTION MEDICINE / TOXICOLOGY AND ALCOHOLOGY"},
    {value: "YW", label: "EMERGENCY MEDICINE OR URGENT CARE"},
    {value: "33", label: "ALLERGY AND IMMUNOLOGY"},
    {value: "01", label: "ANATOMIC AND CYTOPATHOLOGIC PATHOLOGY"},
    {value: "DEC03", label: "ANDROLOGY"},
    {value: "02", label: "ANESTHESIOLOGY AND INTENSIVE CARE"},
    {value: "34", label: "ANGIOLOGY / VASCULAR MEDICINE"},
    {value: "Y1", label: "HORMONAL AND METABOLIC BIOCHEMISTRY"},
    {value: "Y2", label: "BIOLOGY OF INFECTIOUS AGENTS"},
    {value: "04", label: "MEDICAL BIOLOGY"},
    {value: "BMA", label: "MEDICAL BIOLOGY OPTION INFECTIOUS AGENTS"},
    {
      value: "BMR",
      label: "MEDICAL BIOLOGY OPTION REPRODUCTIVE BIOLOGY",
    },
    {value: "BMG", label: "MEDICAL BIOLOGY OPTION GENERAL BIOLOGY"},
    {
      value: "BMH",
      label: "MEDICAL BIOLOGY OPTION HEMATOLOGY AND IMMUNOLOGY",
    },
    {
      value: "BMM",
      label:
        "MEDICAL BIOLOGY OPTION MOLECULAR MEDICINE, GENETICS AND PHARMACOLOGY",
    },
    {value: "Y3", label: "MOLECULAR BIOLOGY"},
    {value: "35", label: "ONCOLOGY"},
    {value: "DEC07", label: "ONCOLOGY OPTION BIOLOGY IN ONCOLOGY"},
    {value: "DEC05", label: "ONCOLOGY OPTION ONCOLOGICAL SURGERY"},
    {value: "DEC08", label: "ONCOLOGY OPTION IMAGING IN ONCOLOGY"},
    {value: "DEC06", label: "ONCOLOGY OPTION CANCER NETWORKS"},
    {
      value: "DEC04",
      label: "ONCOLOGY OPTION MEDICAL TREATMENT OF CANCERS",
    },
    {value: "06", label: "CARDIOLOGY AND VASCULAR DISEASES"},
    {value: "83", label: "FACIAL AND NECK SURGERY"},
    {value: "08", label: "GENERAL SURGERY"},
    {value: "68", label: "PEDIATRIC SURGERY"},
    {value: "CMF", label: "MAXILLOFACIAL SURGERY (REFORM 2017)"},
    {value: "10", label: "MAXILLOFACIAL SURGERY AND STOMATOLOGY"},
    {value: "COR", label: "ORAL SURGERY"},
    {value: "12", label: "ORTHOPEDIC SURGERY AND TRAUMATOLOGY"},
    {value: "CPV", label: "PEDIATRIC SURGERY, VISCERAL SURGERY OPTION"},
    {value: "CPO", label: "PEDIATRIC SURGERY, ORTHOPEDIC SURGERY OPTION"},
    {value: "09", label: "PLASTIC, RECONSTRUCTIVE AND AESTHETIC SURGERY"},
    {value: "11", label: "THORACIC AND CARDIOVASCULAR SURGERY"},
    {value: "13", label: "UROLOGICAL SURGERY"},
    {value: "82", label: "VASCULAR SURGERY"},
    {value: "88", label: "VISCERAL AND DIGESTIVE SURGERY"},
    {value: "Y4", label: "HUMAN CYTOGENETICS"},
    {value: "14", label: "DERMATOLOGY AND VENEROLOGY"},
    {value: "DEC09", label: "DERMATOPATHOLOGY"},
    {value: "37", label: "ENDOCRINOLOGY AND METABOLISM"},
    {value: "EDN", label: "ENDOCRINOLOGY-DIABETOLOGY-NUTRITION"},
    {value: "ZV", label: "EVALUATION AND TREATMENT OF PAIN"},
    {value: "DEC10", label: "FETOPATHOLOGY"},
    {value: "28", label: "GASTROENTEROLOGY AND HEPATOLOGY"},
    {value: "72", label: "MEDICAL GENETICS"},
    {value: "94", label: "GERIATRICS / GERONTOLOGY"},
    {value: "24", label: "MEDICAL GYNECOLOGY"},
    {value: "246", label: "MEDICAL GYNECOLOGY AND OBSTETRICS"},
    {value: "21", label: "OBSTETRICS AND GYNECOLOGY / OBSTETRICS"},
    {value: "38", label: "HEMATOLOGY"},
    {value: "HEM", label: "HEMATOLOGY (REFORM 2017)"},
    {value: "Y5", label: "BIOLOGICAL HEMATOLOGY"},
    {value: "HS", label: "HEMATOLOGY OPTION BLOOD DISEASES"},
    {value: "96", label: "HEMATOLOGY OPTION ONCO-HEMATOLOGY"},
    {value: "DEC11", label: "Hemobiology-transfusion / transfusion technology"},
    {value: "HGE", label: "Hepato-gastro-enterology"},
    {value: "71", label: "Hydrology and medical climatology"},
    {value: "YI", label: "Immunology and immunopathology"},
    {value: "MIT", label: "Infectious and tropical diseases"},
    {value: "Z5", label: "Aerospace medicine"},
    {value: "MCV", label: "Cardiovascular medicine"},
    {value: "DEC15", label: "Emergency medicine"},
    {value: "Z7", label: "Disaster medicine"},
    {value: "YYC", label: "Pain medicine and palliative medicine"},
    {
      value: "DEC13",
      label:
        "Pain medicine and palliative medicine (option pain medicine and option palliative medicine)",
    },
    {value: "DEC14", label: "Reproductive medicine"},
    {value: "YR", label: "Reproductive medicine and medical gynecology"},
    {value: "05", label: "Sports medicine"},
    {value: "41", label: "Occupational medicine"},
    {value: "STR", label: "Medicine and health at work"},
    {value: "90", label: "General medicine"},
    {value: "MIR", label: "Intensive care medicine"},
    {value: "32", label: "Internal medicine"},
    {value: "MII", label: "Internal medicine and clinical immunology"},
    {value: "40", label: "Forensic medicine and medical expertise"},
    {value: "69", label: "Nuclear medicine"},
    {value: "Z8", label: "Penitentiary medicine"},
    {value: "59", label: "Physical medicine and rehabilitation"},
    {value: "MV", label: "Vascular medicine"},
    {value: "DEC18", label: "Neonatology"},
    {value: "YY", label: "Neonatology (decree of 19.10.2001)"},
    {value: "30", label: "Nephrology"},
    {value: "44", label: "Neurosurgery"},
    {value: "42", label: "Neurology"},
    {value: "425", label: "Neurology and psychiatry"},
    {value: "DEC19", label: "Neuropathology"},
    {value: "YYA", label: "Neuropathology (decree of 24.04.2002)"},
    {value: "36", label: "Nutrition"},
    {value: "78", label: "Medical oncology option"},
    {value: "98", label: "Oncology option onco-hematology"},
    {value: "OOM", label: "Medical oncology option"},
    {value: "OOT", label: "Oncology option radiotherapy"},
    {value: "18", label: "ONCOLOGY - RADIOTHERAPY OPTION"},
    {value: "48", label: "OPHTHALMOLOGY"},
    {
      value: "99",
      label: "EAR, NOSE AND THROAT (ENT) AND HEAD AND NECK SURGERY",
    },
    {value: "76", label: "ORTHOPEDIC DENTO-MAXILLO-FACIAL SURGERY"},
    {value: "49", label: "OTORHINOLARYNGOLOGY (ENT)"},
    {
      value: "31",
      label: "INFECTIOUS AND TROPICAL PATHOLOGY, CLINICAL AND BIOLOGICAL",
    },
    {value: "50", label: "PEDIATRICS"},
    {value: "Y6", label: "PHARMACOKINETICS AND DRUG METABOLISM"},
    {
      value: "DEC23",
      label: "CLINICAL PHARMACOLOGY AND EVALUATION OF THERAPEUTICS",
    },
    {value: "52", label: "PHONIATRY"},
    {value: "53", label: "PULMONOLOGY"},
    {value: "ZJ", label: "MEDICAL LEGAL PRACTICES"},
    {value: "46", label: "PSYCHIATRY"},
    {value: "56", label: "CHILD AND ADOLESCENT PSYCHIATRY"},
    {value: "16", label: "RADIO-DIAGNOSTICS AND MEDICAL IMAGING"},
    {value: "178", label: "RADIO-DIAGNOSTICS AND RADIOTHERAPY"},
    {value: "RIM", label: "RADIOLOGY AND MEDICAL IMAGING"},
    {value: "Y7", label: "RADIOPHARMACY AND RADIOBIOLOGY"},
    {value: "DR", label: "INTENSIVE CARE MEDICINE"},
    {value: "39", label: "MEDICAL INTENSIVE CARE"},
    {value: "RM", label: "MEDICAL RESEARCH"},
    {value: "61", label: "RHEUMATOLOGY"},
    {value: "SP", label: "PUBLIC HEALTH"},
    {value: "79", label: "PUBLIC HEALTH AND SOCIAL MEDICINE"},
    {value: "63", label: "STOMATOLOGY"},
    {value: "Y8", label: "BIOLOGICAL TOXICOLOGY"},
    {value: "UR", label: "UROLOGY"},
  ],

  orientations: [
    {label: "Choose an orientation", value: ""},
    {label: "Acupuncture", value: "1"},
    {label: "Homeopathy", value: "2"},
    {label: "Acupuncture and Homeopathy", value: "3"},
  ],

  titles: [
    {value: "", label: "Choose a title"},
    {value: "AC", label: "Acupuncture"},
    {
      value: "38",
      label: "EU Certificate in Vertebrotherapy and Manual Medicine",
    },
    {
      value: "24",
      label: "EU Certificate in Legal Compensation for Bodily Injury",
    },
    {value: "88", label: "EU Certificate in General Ultrasound Studies"},
    {value: "72", label: "Certificate in Manual Therapy and Physical Medicine"},
    {
      value: "99",
      label:
        "Certificate in Complementary Studies in Hepato-gastro-enterology Ultrasound",
    },
    {
      value: "A8",
      label:
        "Certificate in Complementary Studies in Ultrasound with Echotomography option",
    },
    {value: "05", label: "Certificate in Digestive Endoscopy Studies"},
    {
      value: "04",
      label: "Certificate in Clinical Electroencephalography Studies",
    },
    {value: "07", label: "Certificate in Leprosy Studies"},
    {value: "57", label: "Certificate in Advanced Proctology Studies"},
    {value: "96", label: "Certificate of Training in Osteodensitometry"},
    {
      value: "06",
      label: "Certificate in Neuro-muscular Functional Exploration Studies",
    },
    {value: "A3", label: "Authorization for Propharmacy"},
    {
      value: "87",
      label:
        "Special Education EU Certificates in Gynecology and Obstetrics Ultrasound",
    },
    {value: "01", label: "EU Certificate in Aerospace Medicine"},
    {
      value: "84",
      label:
        "EU Certificate in the Application of Ultrasound in Obstetrics and Gynecology",
    },
    {
      value: "A4",
      label: "Clinical Ultrasound EU Certificate (formerly authorized degree)",
    },
    {value: "C4", label: "Medical Ultrasonography University Certificate"},
    {
      value: "94",
      label: "Medical-Surgical Proctology University Certificate",
    },
    {
      value: "03",
      label: "Clinical Studies Certificate with a mention in Orthodontics",
    },
    {
      value: "42",
      label:
        "Expertise of Body Injury University Certificate or Diploma (CAPEDOC)",
    },
    {value: "B0", label: "University Diploma in Ultrasonography"},
    {value: "71", label: "Gerontology and Geriatrics State Diploma"},
    {
      value: "41",
      label: "Legal Reparation of Body Injury Diploma of Medical Studies",
    },
    {
      value: "C5",
      label: "Hyperbaric Medicine and Diving Medicine Inter-University Diploma",
    },
    {
      value: "67",
      label:
        "Polyarthritis and Systemic Diseases Inter-University Diploma in Advanced Studies",
    },
    {
      value: "76",
      label:
        "Physiology and Pathology of Sleep Inter-University Diploma (Grenoble-Lyon)",
    },
    {
      value: "D8",
      label: "Medical-Legal Expertise Inter-University Diploma",
    },
    {
      value: "35",
      label: "Pediatric Emergency Reception Inter-University Diploma",
    },
    {value: "17", label: "Acupuncture Inter-University Diploma"},
    {
      value: "B8",
      label: "Palliative Care and Support Inter-University Advanced Diploma",
    },
    {value: "B6", label: "Medical Expertise Aptitude Inter-University Diploma"},
    {value: "32", label: "Arthroscopy Inter-University Diploma"},
    {value: "E5", label: "Cardio-Oncology Inter-University Diploma"},
    {value: "33", label: "Interventional Cardiology Inter-University Diploma"},
    {
      value: "50",
      label: "Digestive Cancer Surgery Inter-University Diploma",
    },
    {
      value: "47",
      label: "Endocrine and Metabolic Surgery Inter-University Diploma",
    },
    {value: "56", label: "Vitreoretinal Surgery Inter-University Diploma"},
    {value: "20", label: "Hand Surgery Inter-University Diploma"},
    {
      value: "63",
      label: "Foot and Ankle Surgery Inter-University Diploma",
    },
    {value: "C0", label: "Spinal Surgery Inter-University Diploma"},
    {
      value: "25",
      label: "Refractive Surgery of Cataract-Myopia Inter-University Diploma",
    },
    {value: "89", label: "Laparoscopic Surgery Inter-University Diploma"},
    {
      value: "73",
      label:
        "Aesthetic Dermatology, Laser Dermatology and Cosmetology Inter-University Diploma",
    },
    {value: "34", label: "D.I.U. Dermatology Aesthetics and Cosmetology"},
    {value: "65", label: "D.I.U. Medical-Legal Expertise Law"},
    {
      value: "64",
      label: "D.I.U. Cardiac and Mediterranean Vascular Echocardiography",
    },
    {value: "60", label: "D.I.U. Echocardiography and Doppler"},
    {
      value: "21",
      label: "D.I.U. Gynecological and Obstetrical Ultrasound",
    },
    {value: "48", label: "D.I.U. Vascular Ultrasound"},
    {
      value: "43",
      label: "D.I.U. Vascular and Urinary Ultrasound",
    },
    {
      value: "52",
      label: "D.I.U. Abdominal and Urinary Ultrasound",
    },
    {
      value: "66",
      label: "D.I.U. Ultrasound Specialty Option Ultrasound",
    },
    {
      value: "B3",
      label: "D.I.U. Pediatric Endocrinology and Diabetology",
    },
    {
      value: "97",
      label: "D.I.U. Interventional Digestive Endoscopy",
    },
    {
      value: "93",
      label: "D.I.U. Higher Education in Neuroradiology",
    },
    {value: "A7", label: "D.I.U. Epileptology"},
    {
      value: "69",
      label: "D.I.U. Studies of Chronic Inflammatory Bowel Diseases",
    },
    {
      value: "A2",
      label: "D.I.U. Medical Accident Expertise",
    },
    {
      value: "55",
      label: "D.I.U. Digestive Functional Explorations",
    },
    {
      value: "44",
      label: "D.I.U. Non-invasive Vascular Imaging",
    },
    {value: "49", label: "D.I.U. Sleep and its Pathology"},
    {
      value: "68",
      label: "D.I.U. Respiratory and Allergic Diseases in Children",
    },
    {value: "B9", label: "D.I.U. Migraine and Headaches"},
    {
      value: "D7",
      label: "D.I.U. Manual Medicine - Medical Osteopathy",
    },
    {
      value: "15",
      label: "D.I.U. Manual Medicine and Osteopathy",
    },
    {
      value: "62",
      label: "D.I.U. Morphological Medicine and Anti-Aging",
    },
    {
      value: "D0",
      label: "D.I.U. Applied Sleep Medicine in Gerontology",
    },
    {
      value: "61",
      label: "D.I.U. Neonatal Medicine and Resuscitation",
    },
    {
      value: "A1",
      label: "D.I.U. Orthopedic Manual Medicine Osteopathy",
    },
    {
      value: "19",
      label: "D.I.U. Subaquatic and Hyperbaric Medicine",
    },
    {value: "39", label: "D.I.U. Mesotherapy"},
    {value: "A0", label: "D.I.U. Onco-urology"},
    {value: "E1", label: "D.I.U. Medico-surgical Pancreatologie"},
    {value: "27", label: "D.I.U. Neuro-Vascular Pathology"},
    {value: "86", label: "D.I.U. Surgical Retinal-Vitreous Pathology"},
    {value: "30", label: "D.I.U. Sleep and Vigilance Pathology"},
    {
      value: "E2",
      label: "D.I.U. Orbital-Palpebral-Lacrymal Pathology and Surgery (OPL)",
    },
    {value: "31", label: "D.I.U. Fetal and Placental Pathology"},
    {value: "98", label: "D.I.U. Medical bone pathologies"},
    {value: "29", label: "D.I.U. Phoniatrics"},
    {
      value: "54",
      label: "D.I.U. Neurosensory function exploration and pathophysiology",
    },
    {value: "C9", label: "D.I.U. Pediatric pulmonology"},
    {value: "C7", label: "D.I.U. Medical practice in thermal resort"},
    {value: "91", label: "D.I.U. Instrumental medical proctology"},
    {value: "90", label: "D.I.U. Cardiac rhythm and pacing"},
    {value: "36", label: "D.I.U. Legal compensation of bodily harm"},
    {value: "E6", label: "D.I.U. Child Health Preventive Option"},
    {value: "C3", label: "D.I.U. Caring for caregivers"},
    {value: "46", label: "D.I.U. Palliative care"},
    {value: "16", label: "D.I.U. Palliative care and accompaniment"},
    {value: "37", label: "D.I.U. Cardiac pacing"},
    {value: "18", label: "D.I.U. Smoking cessation and tobacco addiction"},
    {value: "26", label: "D.I.U. Vigilance and Sleep"},
    {value: "B5", label: "D.I.U. Prosthetics"},
    {value: "C6", label: "D.I.U. OCT in ophthalmology"},
    {value: "D4", label: "D.I.U. Laryngo-Phoniatics"},
    {value: "B7", label: "D.I.U. Clinical Neurophysiology"},
    {value: "14", label: "D.I.U. Sexology"},
    {
      value: "D6",
      label: "D.I.U. Non-invasive cardiovascular echocardiography and imaging",
    },
    {value: "23", label: "D.I.U. or D.U. Echocardiography"},
    {value: "11", label: "D.I.U. or D.U. General ultrasound"},
    {value: "10", label: "D.I.U. or D.U. Proctology"},
    {
      value: "77",
      label: "D.I.U. or D.U. or C.U. Radiology oto-neuro ophthalmology",
    },
    {
      value: "81",
      label: "D.U. (or Certificate) Orthopedic medicine and manual therapies",
    },
    {value: "28", label: "D.U. Contact lens adaptation"},
    {value: "22", label: "D.U. Angiography and retinal pathology"},
    {
      value: "74",
      label: "D.U. Cardiovascular echocardiography and echo-doppler",
    },
    {value: "92", label: "D.U. Cardiac ultrasound"},
    {
      value: "45",
      label: "D.U. Studies on the repair of bodily harm",
    },
    {
      value: "59",
      label: "D.U. Studies on the repair of bodily harm opt physician",
    },
    {
      value: "75",
      label: "D.U. Geriatrics and Medical Social Gerontology",
    },
    {
      value: "53",
      label: "D.U. Indemnification for bodily harm...company medical advisor",
    },
    {
      value: "58",
      label: "D.U. Ultrasonic Methods in Medicine",
    },
    {
      value: "D5",
      label: "D.U. Osteopathy Manual Medicine",
    },
    {
      value: "C8",
      label: "D.U. Clinical and Functional Osteopathy",
    },
    {
      value: "40",
      label: "D.U. Legal Repair of Bodily Harm",
    },
    {
      value: "85",
      label: "D.U. Legal Repair of Bodily Harm opt. S.S. and Legislation",
    },
    {
      value: "E4",
      label:
        "D.U. Diagnostic and Therapeutic Techniques in Endovenous Phlebology Intervention",
    },
    {
      value: "78",
      label: "D.U. Gerontology and Geriatrics (Limoges as of 01/01/1990)",
    },
    {
      value: "D2",
      label: "D.U. or D.I.U. Imaging and Retinal Pathology",
    },
    {
      value: "51",
      label: "D.U. or D.I.U. Fetal Medicine",
    },
    {
      value: "E0",
      label: "D.U. or D.I.U. Phlebology",
    },
    {
      value: "E3",
      label: "Advanced Techniques in Phlebology D.I.U.",
    },
    {
      value: "95",
      label:
        "Diploma (or certificate of studies) in Clinical Electroencephalography",
    },
    {
      value: "79",
      label: "Diploma in Implantology",
    },
    {
      value: "02",
      label: "Diploma in motor handicapped devices",
    },
    {
      value: "70",
      label: "Diploma in Clinical Gerontology",
    },
    {
      value: "A9",
      label:
        "Diploma in Neuro-pediatrics from the Free University of Brussels (Belgium)",
    },
    {
      value: "A6",
      label: "Diploma from the Institute of Agricultural Medicine in Tours",
    },
    {
      value: "08",
      label: "Diploma of Merchant Marine",
    },
    {
      value: "09",
      label: "Diploma in Manual Therapeutics",
    },
    {
      value: "B4",
      label: "Diploma in Compensation for Bodily Harm (Bordeaux II)",
    },
    {
      value: "13",
      label: "Podiatry degrees",
    },
    {
      value: "12",
      label: "Related degrees + legal repair of bodily harm",
    },
    {
      value: "C1",
      label: "Doctorate in Sciences (+ option)",
    },
    {
      value: "A5",
      label: "Exceptional training in occupational medicine",
    },
    {
      value: "HO",
      label: "Homeopathy",
    },
    {
      value: "C2",
      label: "Hospital hygiene and environmental medicine",
    },
    {
      value: "D9",
      label: "Winner of the National Academy of Medicine",
    },
    {
      value: "80",
      label: "Sexually transmitted diseases",
    },
    {
      value: "82",
      label: "Osteopathy by prefectural or ARS decree",
    },
    {
      value: "B2",
      label: "Psychotherapist by ARS authorization",
    },
    {
      value: "D3",
      label: "Validation of a DPC in Medical Otology",
    },
    {
      value: "D1",
      label: "Validation of a DPC in Prescription of PPC device",
    },
  ],

  regions: [
    {value: "", label: "Choose a region..."},
    {value: 1, label: "Northeast Region"},
    {value: 2, label: "Southeast Region"},
    {value: 3, label: "Midwest Region"},
    {value: 4, label: "Southwest Region"},
    {value: 5, label: "West Region"},
  ],

  departments: [
    {value: "", label: "Choose a department...", region: 0},
    {value: "", label: "Choose a department...", region: 1},
    {value: "", label: "Choose a department...", region: 2},
    {value: "", label: "Choose a department...", region: 3},
    {value: "", label: "Choose a department...", region: 4},
    {value: "", label: "Choose a department...", region: 5},

    {value: 1, label: "Maine", region: 1},
    {value: 2, label: "New Hampshire", region: 1},
    {value: 3, label: "Vermont", region: 1},
    {value: 4, label: "Massachusetts", region: 1},
    {value: 5, label: "Rhode Island", region: 1},
    {value: 6, label: "Connecticut", region: 1},
    {value: 7, label: "New York", region: 1},
    {value: 8, label: "New Jersey", region: 1},
    {value: 9, label: "Pennsylvania", region: 1},

    {value: 10, label: "Virginia", region: 2},
    {value: 11, label: "West Virginia", region: 2},
    {value: 12, label: "Delaware", region: 2},
    {value: 13, label: "North Carolina", region: 2},
    {value: 14, label: "South Carolina", region: 2},
    {value: 15, label: "Georgia", region: 2},
    {value: 16, label: "Florida", region: 2},
    {value: 17, label: "Kentucky", region: 2},
    {value: 18, label: "Tennessee", region: 2},
    {value: 19, label: "Mississippi", region: 2},
    {value: 20, label: "Alabama", region: 2},
    {value: 21, label: "Arkansas", region: 3},

    {value: 22, label: "Ohio", region: 3},
    {value: 23, label: "Indiana", region: 3},
    {value: 24, label: "Illinois", region: 3},
    {value: 25, label: "Michigan", region: 3},
    {value: 26, label: "Wisconsin", region: 3},
    {value: 27, label: "Minnesota", region: 3},
    {value: 28, label: "Iowa", region: 3},
    {value: 29, label: "Missouri", region: 3},
    {value: 30, label: "North Dakota", region: 3},
    {value: 31, label: "South Dakota", region: 3},
    {value: 32, label: "Nebraska", region: 3},
    {value: 33, label: "Kansas", region: 3},

    {value: 34, label: "Texas", region: 4},
    {value: 35, label: "Oklahoma", region: 4},
    {value: 36, label: "New Mexico", region: 4},
    {value: 37, label: "Arizona", region: 4},
    {value: 38, label: "Colorado", region: 4},

    {value: 39, label: "California", region: 5},
    {value: 40, label: "Oregon", region: 5},
    {value: 41, label: "Washington", region: 5},
    {value: 42, label: "Alaska", region: 5},
    {value: 43, label: "Hawaii", region: 5},
  ],
};
